# Generated by Django 4.0.3 on 2022-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MUNICIPALITY', 'Municipality'), ('COOPERATIVE', 'Cooperative')], max_length=20, verbose_name='Types')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('zip_code', models.CharField(max_length=20, verbose_name='zip code')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'ordering': ['-id'],
            },
        ),
    ]
