# Generated by Django 4.0.3 on 2022-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOCAL', 'Local'), ('CLEANSTOCK', 'CleanStock')], max_length=30, verbose_name='Types')),
                ('partner_type', models.CharField(blank=True, choices=[('BANK', 'Bank'), ('SERVICE PROVIDER', 'Service Provider'), ('ENERGY COMPANY', 'Energy Company')], max_length=30, null=True, verbose_name='Partner_Types')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('nip_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='nip number')),
                ('zip_code', models.CharField(max_length=20, verbose_name='zip code')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='city')),
                ('communities', models.ManyToManyField(blank=True, to='communities.community')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['-id'],
            },
        ),
    ]
