# Generated by Django 4.0.4 on 2022-04-20 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('CLEANSTOCK', 'CleanStock')], max_length=30, null=True, verbose_name='Types')),
                ('partner_type', models.CharField(blank=True, choices=[('BANK', 'Bank'), ('SERVICE PROVIDER', 'Service Provider'), ('ENERGY COMPANY', 'Energy Company')], max_length=30, null=True, verbose_name='Partner_Types')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('nip_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='nip number')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='zip code')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='city')),
                ('energy_tariff', models.CharField(blank=True, max_length=30, null=True, verbose_name='energy tariff')),
                ('pv_technology', models.CharField(blank=True, max_length=30, null=True, verbose_name='pv technology')),
                ('pv_power_peak_installed', models.IntegerField(blank=True, null=True, verbose_name='pv power peak installed')),
                ('system_loss', models.IntegerField(blank=True, null=True, verbose_name='system loss')),
                ('mounting_position', models.CharField(blank=True, max_length=20, null=True, verbose_name='mounting position')),
                ('slope', models.IntegerField(blank=True, null=True, verbose_name='slope')),
                ('azimuth', models.IntegerField(blank=True, null=True, verbose_name='azimuth')),
                ('communities', models.ManyToManyField(blank=True, to='communities.community')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
                ('users', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-id'],
            },
        ),
    ]
