# Generated by Django 4.0.3 on 2022-03-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROSPECT', 'Prospect'), ('SCHOOL', 'School'), ('PROSUMENT', 'Prosument'), ('BENEFICIARY', 'Beneficiary')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('organization_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='organization name')),
                ('nip_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='nip number')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('zip_code', models.CharField(max_length=10, verbose_name='zip code')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='city')),
                ('energy_tariff', models.CharField(blank=True, max_length=30, null=True, verbose_name='energy tariff')),
                ('pv_technology', models.CharField(blank=True, max_length=30, null=True, verbose_name='pv technology')),
                ('pv_power_peak_installed', models.IntegerField(blank=True, null=True, verbose_name='pv power peak installed')),
                ('system_loss', models.IntegerField(blank=True, null=True, verbose_name='system loss')),
                ('mounting_position', models.CharField(blank=True, max_length=20, null=True, verbose_name='mounting position')),
                ('slope', models.IntegerField(blank=True, null=True, verbose_name='slope')),
                ('azimuth', models.IntegerField(blank=True, null=True, verbose_name='azimuth')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-id'],
            },
        ),
    ]
