# Generated by Django 4.0.4 on 2022-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(blank=True, choices=[('PROSPECT', 'Prospect'), ('SCHOOL', 'School'), ('PROSUMENT', 'Prosument'), ('BENEFICIARY', 'Beneficiary')], max_length=30, null=True),
        ),
    ]
